### ISSUE TITLE
Transform Issue After Importation

### ISSUE THREAD

**Issue by jcoll44** [omichel/urdf2webots#11]
With some models after importation the transforms and joints axis/angle are wrong.

For example when importing the URDF of the kinova arm (m1n6s300_standalone.xacro) from [kinova-ros](https://github.com/Kinovarobotics/kinova-ros) the result once imported in Webots is wrong:

[m1n6s300_standalone.zip](https://github.com/omichel/urdf2webots/files/2750159/m1n6s300_standalone.zip)

### Result after importation
![image](https://user-images.githubusercontent.com/26240969/50626497-61a2d980-0f7a-11e9-9634-b4722ba21790.png)
[M1n6s300.zip](https://github.com/omichel/urdf2webots/files/2750276/M1n6s300.zip)

**Comment by DavidMansolino** [comment]
Thank you for your bug report.
You are welcome to contribute if you want to fix this bug.
Otherwise, we will try to fix it as soon as we have time.

**Comment by DavidMansolino** [comment]
In the meantime you can manually fix the axes issue following these steps:
  1. Add the robot in the world.
  2. Convert it to base node by right clicking on the robot in the scene-tree and pressing on 'Convert to Base Node(s)'.
  3. You can now directly edit the axes in the scene-tree.

If you want Cyberbotics to do this for you do not hesitate to contact support@cyberbotics.com

**Comment by DavidMansolino** [comment]
Fixed in #12
